export const OFFICE_CONSTANTS = {
  floorHeight: 4.8,
  eyeHeight: 1.65,
  moveSpeed: 5.4,
  sprintMultiplier: 1.85,
  interactDistance: 4.2
};

export const AGENTS = [
  {
    id: 'maya-pm',
    name: 'Maya',
    role: 'Kaggle Project Manager',
    floor: 1,
    room: 'Lobby',
    position: [-15, 0, -10],
    color: '#2354d1',
    waypoints: [[-15, 0, -10], [-19.2, 0, -10.2], [-18.6, 0, -7.2], [-13.2, 0, -8.4]],
    defaultActivity: 'working',
    activitySet: ['working', 'walking', 'thinking'],
    expertise: ['alur kompetisi', 'milestone', 'prioritas eksperimen', 'decision log'],
    voiceHint: 'id-ID',
    system: 'Anda adalah project manager kompetisi Kaggle. Fokus pada struktur kerja, prioritas, pembagian tugas, risiko deadline, dan keputusan yang dapat dieksekusi.',
    opener: 'Saya Maya. Berikan link/brief kompetisi, lalu saya bantu susun alur kerja dan prioritas eksperimen.'
  },
  {
    id: 'raka-data',
    name: 'Raka',
    role: 'Data Engineer',
    floor: 1,
    room: 'Data Lab',
    position: [-16, 0, 5],
    color: '#0f766e',
    waypoints: [[-16, 0, 5], [-18.8, 0, 2.3], [-12.2, 0, 2.8], [-11.6, 0, 7.8]],
    defaultActivity: 'typing',
    activitySet: ['typing', 'walking', 'reading'],
    expertise: ['data ingestion', 'schema', 'missing value', 'leakage awal'],
    voiceHint: 'id-ID',
    system: 'Anda adalah data engineer untuk kompetisi Kaggle. Fokus pada memahami struktur data, file, join key, quality check, pipeline, dan pencegahan leakage.',
    opener: 'Saya Raka. Saya akan pastikan data pipeline rapi sebelum kita terlalu cepat modeling.'
  },
  {
    id: 'sinta-eda',
    name: 'Sinta',
    role: 'EDA Analyst',
    floor: 1,
    room: 'Data Lab',
    position: [-11.2, 0, 7.2],
    color: '#7c3aed',
    waypoints: [[-11.2, 0, 7.2], [-15.7, 0, 8.6], [-18.2, 0, 5.8], [-12.1, 0, 2.8]],
    defaultActivity: 'whiteboard',
    activitySet: ['whiteboard', 'walking', 'thinking'],
    expertise: ['EDA', 'hypothesis', 'visualisasi', 'feature insight'],
    voiceHint: 'id-ID',
    system: 'Anda adalah analis EDA. Fokus pada eksplorasi data, pola target, segmentasi, outlier, distribusi, dan insight yang bisa mendorong feature engineering.',
    opener: 'Saya Sinta. Saya akan bantu ubah data mentah menjadi hipotesis yang bisa diuji.'
  },
  {
    id: 'bima-ml',
    name: 'Bima',
    role: 'Machine Learning Engineer',
    floor: 1,
    room: 'Model Lab',
    position: [1, 0, 5],
    color: '#ea580c',
    waypoints: [[1, 0, 5], [-3.2, 0, 2.2], [4.8, 0, 3.5], [5.1, 0, 9.8]],
    defaultActivity: 'typing',
    activitySet: ['typing', 'walking', 'thinking'],
    expertise: ['baseline', 'feature engineering', 'modeling', 'ensembling'],
    voiceHint: 'id-ID',
    system: 'Anda adalah ML engineer kompetisi. Fokus pada baseline, model keluarga yang masuk akal, eksperimen bertahap, ensembling, dan trade-off kompleksitas.',
    opener: 'Saya Bima. Jangan langsung deep learning; kita mulai dari baseline yang kuat dan valid.'
  },
  {
    id: 'nadia-val',
    name: 'Nadia',
    role: 'Validation Scientist',
    floor: 1,
    room: 'Model Lab',
    position: [5, 0, 7.5],
    color: '#be123c',
    waypoints: [[5, 0, 7.5], [1.8, 0, 10.2], [-2.8, 0, 8.5], [4.7, 0, 2.2]],
    defaultActivity: 'reading',
    activitySet: ['reading', 'walking', 'thinking'],
    expertise: ['cross-validation', 'metric', 'leakage', 'public/private split'],
    voiceHint: 'id-ID',
    system: 'Anda adalah validation scientist. Fokus pada validasi yang meniru leaderboard private, metric, split strategy, leakage, dan eksperimen yang dapat dipercaya.',
    opener: 'Saya Nadia. Score bagus tanpa validasi yang benar bisa menipu. Kita cek split lebih dulu.'
  },
  {
    id: 'tari-story',
    name: 'Tari',
    role: 'Notebook Storyteller',
    floor: 1,
    room: 'War Room',
    position: [14.6, 0, -7.8],
    color: '#0891b2',
    waypoints: [[14.6, 0, -7.8], [19.2, 0, -7.6], [19.5, 0, -13.2], [14.4, 0, -13.1]],
    defaultActivity: 'whiteboard',
    activitySet: ['whiteboard', 'walking', 'working'],
    expertise: ['notebook', 'narasi', 'visual explanation', 'reproducibility'],
    voiceHint: 'id-ID',
    system: 'Anda adalah notebook storyteller. Fokus pada notebook yang rapi, dapat direproduksi, alur naratif, komentar kode, dan penjelasan insight untuk portofolio.',
    opener: 'Saya Tari. Kita buat notebook yang bukan hanya jalan, tetapi juga mudah dipahami dan layak portofolio.'
  },
  {
    id: 'dimas-review',
    name: 'Dimas',
    role: 'Peer Reviewer',
    floor: 2,
    room: 'Review Room',
    position: [-18.4, 0, -8.2],
    color: '#334155',
    waypoints: [[-18.4, 0, -8.2], [-12.4, 0, -7.6], [-11.8, 0, -12.4], [-19.6, 0, -12.3]],
    defaultActivity: 'reading',
    activitySet: ['reading', 'walking', 'thinking'],
    expertise: ['review kode', 'audit metodologi', 'anti-overfit', 'submission checklist'],
    voiceHint: 'id-ID',
    system: 'Anda adalah peer reviewer yang kritis. Fokus mencari kelemahan metodologi, bug, overfitting, kebocoran data, dan blind spot sebelum submission.',
    opener: 'Saya Dimas. Saya akan berperan sebagai reviewer yang agak galak supaya submission kita lebih aman.'
  },
  {
    id: 'lana-mentor',
    name: 'Lana',
    role: 'Learning Mentor',
    floor: 2,
    room: 'Learning Studio',
    position: [12, 0, 7],
    color: '#16a34a',
    waypoints: [[12, 0, 7], [18.4, 0, 3.2], [19.4, 0, 11.2], [13.2, 0, 11.4]],
    defaultActivity: 'whiteboard',
    activitySet: ['whiteboard', 'walking', 'working'],
    expertise: ['pembelajaran konsep', 'tutorial bertahap', 'analogi', 'latihan'],
    voiceHint: 'id-ID',
    system: 'Anda adalah mentor pembelajaran. Fokus mengajar konsep ML/Kaggle secara bertahap, bahasa sederhana, contoh praktis, dan latihan kecil.',
    opener: 'Saya Lana. Ketika konsep terasa kabur, kita pecah menjadi langkah kecil sampai benar-benar paham.'
  }
];

export const WORKFLOW = [
  { id: 'intake', title: 'Baca brief kompetisi', detail: 'Metric, deadline, rules, ukuran data, format submission, dan batasan komputasi.' },
  { id: 'download', title: 'Download dan katalog file', detail: 'Catat semua file, kolom, target, sample submission, dan relasi antar tabel.' },
  { id: 'eda', title: 'EDA terarah', detail: 'Distribusi target, missing values, outlier, leakage candidate, dan baseline hypothesis.' },
  { id: 'validation', title: 'Desain validasi', detail: 'CV/split yang paling meniru private leaderboard; jangan percaya public score saja.' },
  { id: 'baseline', title: 'Baseline reproducible', detail: 'Notebook pertama harus sederhana, cepat, dan punya decision log.' },
  { id: 'features', title: 'Feature engineering', detail: 'Uji fitur berdasarkan hipotesis, bukan menambah fitur secara acak.' },
  { id: 'modeling', title: 'Model family comparison', detail: 'Bandingkan model dengan seed, fold, metric, dan waktu training yang tercatat.' },
  { id: 'error', title: 'Error analysis', detail: 'Cari segmen yang gagal, label noise, hard cases, dan pola overfit.' },
  { id: 'ensemble', title: 'Ensemble dan calibration', detail: 'Gabungkan model hanya jika validasi membaik dan variasi model masuk akal.' },
  { id: 'submit', title: 'Submission ritual', detail: 'Cek format file, notebook reproducibility, message submission, dan hasil leaderboard.' },
  { id: 'postmortem', title: 'Post-mortem', detail: 'Catat apa yang berhasil, gagal, dan pelajaran untuk kompetisi berikutnya.' }
];

export const ROOMS = [
  { id: 'lobby', name: 'Lobby & Onboarding', floor: 1, x1: -22, x2: -8, z1: -15, z2: -5, theme: 'reception' },
  { id: 'workspace', name: 'Open Workspace', floor: 1, x1: -6, x2: 10, z1: -15, z2: -3, theme: 'open office' },
  { id: 'warroom', name: 'Glass War Room', floor: 1, x1: 12, x2: 22, z1: -16, z2: -5, theme: 'meeting' },
  { id: 'datalab', name: 'Data Lab', floor: 1, x1: -22, x2: -8, z1: -3, z2: 11, theme: 'data' },
  { id: 'modellab', name: 'Model Lab', floor: 1, x1: -6, x2: 8, z1: 0, z2: 13, theme: 'ml' },
  { id: 'lounge', name: 'Bright Lounge', floor: 1, x1: 10, x2: 22, z1: 0, z2: 14, theme: 'break' },
  { id: 'review', name: 'Review Room', floor: 2, x1: -22, x2: -8, z1: -15, z2: -5, theme: 'audit' },
  { id: 'command', name: 'Leaderboard Command', floor: 2, x1: -6, x2: 10, z1: -15, z2: -3, theme: 'monitoring' },
  { id: 'library', name: 'Research Library', floor: 2, x1: 12, x2: 22, z1: -16, z2: -5, theme: 'reading' },
  { id: 'focus', name: 'Quiet Focus Pods', floor: 2, x1: -22, x2: -8, z1: -3, z2: 11, theme: 'focus' },
  { id: 'studio', name: 'Learning Studio', floor: 2, x1: -6, x2: 8, z1: 0, z2: 13, theme: 'teaching' },
  { id: 'cafeteria2', name: 'Coffee Balcony', floor: 2, x1: 10, x2: 22, z1: 0, z2: 14, theme: 'rest' },
  { id: 'recharge', name: 'Recharge Lounge', floor: 3, x1: -22, x2: -8, z1: -15, z2: 4, theme: 'recharge' },
  { id: 'gaming', name: 'Gaming Zone', floor: 3, x1: -6, x2: 10, z1: -15, z2: 4, theme: 'gaming' },
  { id: 'reflection', name: 'Reflection Pods', floor: 3, x1: 12, x2: 22, z1: -15, z2: 4, theme: 'reflection' },
  { id: 'sky-cafe', name: 'Sky Coffee Bar', floor: 3, x1: -22, x2: 22, z1: 6, z2: 16, theme: 'sky rest' }
];

export const INTERACTIVES = [
  { id: 'onboarding-desk', type: 'onboarding', label: 'Onboarding Desk', floor: 1, position: [-17.3, 0, -13.5], radius: 3.4, hint: 'Tekan E untuk membuka alur kerja awal.' },
  { id: 'main-whiteboard', type: 'whiteboard', label: 'War Room Whiteboard', floor: 1, position: [20.65, 0, -10.5], radius: 2.8, hint: 'Tekan E untuk mengedit whiteboard strategi.' },
  { id: 'meeting-table', type: 'meeting', label: 'Meeting Table', floor: 1, position: [17.2, 0, -10.3], radius: 4.4, hint: 'Tekan E untuk memulai rapat multi-agent.' },
  { id: 'llm-terminal', type: 'llm', label: 'LLM Terminal', floor: 1, position: [5.2, 0, -13.2], radius: 3.2, hint: 'Tekan E untuk mengatur backend LLM.' },
  { id: 'elevator-guide-1', type: 'elevator-guide', label: 'Lift', floor: 1, position: [0, 0, 16.2], radius: 2.4, hint: 'Masuk ke lift, lalu tekan tombol F1/F2/F3 di panel kanan.' },
  { id: 'elevator-guide-2', type: 'elevator-guide', label: 'Lift', floor: 2, position: [0, 0, 16.2], radius: 2.4, hint: 'Masuk ke lift, lalu tekan tombol F1/F2/F3 di panel kanan.' },
  { id: 'elevator-guide-3', type: 'elevator-guide', label: 'Lift', floor: 3, position: [0, 0, 16.2], radius: 2.4, hint: 'Masuk ke lift, lalu tekan tombol F1/F2/F3 di panel kanan.' },
  { id: 'leaderboard-wall', type: 'leaderboard', label: 'Leaderboard Wall', floor: 2, position: [7.5, 0, -14.5], radius: 3.5, hint: 'Tekan E untuk melihat ritual submission dan tracking score.' },
  { id: 'quiz-console', type: 'arcade-game', gameId: 'quiz', label: 'Kaggle Quiz Arcade', floor: 3, position: [-4.5, 0, -10.2], radius: 2.8, hint: 'Tekan E untuk main Kaggle Quiz.' },
  { id: 'leak-hunter-console', type: 'arcade-game', gameId: 'leakHunter', label: 'Leak Hunter', floor: 3, position: [-1.4, 0, -10.2], radius: 2.8, hint: 'Tekan E untuk main Leak Hunter.' },
  { id: 'typing-sprint-console', type: 'arcade-game', gameId: 'typingSprint', label: 'Typing Sprint', floor: 3, position: [1.8, 0, -10.2], radius: 2.8, hint: 'Tekan E untuk main Typing Sprint.' },
  { id: 'memory-match-console', type: 'arcade-game', gameId: 'memoryMatch', label: 'Memory Match', floor: 3, position: [5, 0, -10.2], radius: 2.8, hint: 'Tekan E untuk main Memory Match.' },
  { id: 'recharge-sofa', type: 'recharge', label: 'Recharge Lounge', floor: 3, position: [-16, 0, -6.5], radius: 3.2, hint: 'Tekan E untuk membuka mode istirahat singkat.' },
  { id: 'reflection-board', type: 'reflection', label: 'Reflection Board', floor: 3, position: [13.2, 0, -12.5], radius: 3.2, hint: 'Tekan E untuk catatan post-mortem dan refleksi.' },
  { id: 'coffee-machine-f1', type: 'coffee', label: 'Coffee Machine', floor: 1, position: [11.8, 0, 11.6], radius: 2.2, hint: 'Tekan E untuk brew coffee dan reset fokus singkat.' },
  { id: 'coffee-machine-f3', type: 'coffee', label: 'Sky Coffee Machine', floor: 3, position: [-18.7, 0, 13.6], radius: 2.2, hint: 'Tekan E untuk brew coffee di Sky Coffee Bar.' },
  { id: 'desk-note-data', type: 'desk-note', noteId: 'data-audit', label: 'Data Lab Note', floor: 1, position: [-16.8, 0, 2.25], radius: 1.9, hint: 'Tekan E untuk membaca quick note Data Lab.' },
  { id: 'desk-note-model', type: 'desk-note', noteId: 'baseline', label: 'Model Lab Note', floor: 1, position: [3.2, 0, 7.85], radius: 1.9, hint: 'Tekan E untuk membaca quick note baseline.' },
  { id: 'desk-note-review', type: 'desk-note', noteId: 'review', label: 'Review Room Note', floor: 2, position: [-15.2, 0, -10.2], radius: 1.9, hint: 'Tekan E untuk membaca quick note review.' },
  { id: 'strategy-light', type: 'strategy-light', label: 'War Room Status Light', floor: 1, position: [21.1, 0, -6.1], radius: 2.4, hint: 'Tekan E untuk melihat status strategi War Room.' },
  { id: 'trophy-wall', type: 'trophy-wall', label: 'Achievement Wall', floor: 3, position: [5.2, 0, 16.2], radius: 2.7, hint: 'Tekan E untuk melihat achievement dan best score game.' },
  { id: 'room-directory-f1', type: 'room-directory', label: 'F1 Room Directory', floor: 1, position: [3.4, 0, 17.0], radius: 2.5, hint: 'Tekan E untuk melihat daftar ruangan lantai ini.' },
  { id: 'room-directory-f2', type: 'room-directory', label: 'F2 Room Directory', floor: 2, position: [3.4, 0, 17.0], radius: 2.5, hint: 'Tekan E untuk melihat daftar ruangan lantai ini.' },
  { id: 'room-directory-f3', type: 'room-directory', label: 'F3 Room Directory', floor: 3, position: [3.4, 0, 17.0], radius: 2.5, hint: 'Tekan E untuk melihat daftar ruangan lantai ini.' },
  { id: 'focus-corner', type: 'focus-corner', label: 'Focus Corner', floor: 2, position: [-19.2, 0, 8.2], radius: 2.6, hint: 'Tekan E untuk masuk Focus Mode dan buka workflow kerja.' }
];


